use std::path::Path;
use std::{env, fs};

fn main() {
	let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
	let locales_dir = Path::new(&manifest_dir).join("locales");
	let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
	let out_file = Path::new(&out_dir).join("locales_generated.rs");

	let mut locales: Vec<String> = Vec::new();
	if let Ok(entries) = fs::read_dir(&locales_dir) {
		for e in entries.flatten() {
			if let Some(name) = e.file_name().to_str()
				&& name.ends_with(".yml")
			{
				locales.push(name.trim_end_matches(".yml").to_string());
			}
		}
	}

	if locales.is_empty() {
		locales.push("en-US".to_string());
	}

	locales.sort();

	let mut contents = String::new();
	contents.push_str("// generated by build.rs\n");
	contents.push_str("pub static AVAILABLE_LOCALES: &[&str] = &[");
	for (i, l) in locales.iter().enumerate() {
		if i > 0 {
			contents.push_str(", ");
		}
		contents.push_str(&format!("\"{}\"", l));
	}
	contents.push_str("];\n");

	fs::write(out_file, contents).expect("failed to write locales_generated.rs");

	if env::var("CARGO_CFG_TARGET_OS").ok().as_deref() == Some("windows") {
		let icon_path = "assets/app-icons/chatty.ico";
		if Path::new(icon_path).exists() {
			let mut res = winres::WindowsResource::new();
			res.set_icon(icon_path);
			res.compile().expect("Failed to compile Windows resources");
		}
	}
}
